### ISSUE TITLE
有aarch64  armv8的资料吗？或者有neon比较全面的教程吗？

### ISSUE THREAD

**Issue by pxEkin** [rogerou/Arm-neon-intrinsics#2]

**Comment by rogerou** [comment]
aarch64的话 可以上传一个文档，都是在arm官网上可以找到的。neon教程的话，其实就看arm的那几个教程就好啦
@ToBigboss

**Comment by rogerou** [comment]
#f4249e9

**Comment by rogerou** [comment]
[f4249e9](https://github.com/rogerou/Arm-neon-intrinsics/commit/f4249e960d9fca5e64a28bf5caba79898c99e306)
